### ISSUE TITLE
Create a button component.

### ISSUE THREAD

**Issue by smilegupta** [girlscript-blr/BuildWithGSBlr-Raahat#1]
Create a generic button component which takes the following props 
- children : ReactNode
- type : “button” | “submit” | “reset” - Default is “button”
- variant : “primary” | “secondary” - Default is “secondary”
- isLarge : Boolean - Default is “false”
- onClick : () => void
- disabled: Boolean - Default is false

This should return a button with the given type.
The button should have “children” rendered inside of it.
The button should be of the given variant as provided in the design.
The button should be large if `isLarge` is true.
The button should trigger `onClick` prop when clicked.
The button should be disabled if `disabled` is true.

For design reference [Click Here!](https://www.figma.com/file/TkpKfOPVtQ2XjADFp9Hhbz/Build-with-GS-BLR-Raahat?node-id=1%3A672)
 
**Location to save the component ```src->components->common->button```**

**Comment by ShivangiRai1310** [comment]
Can I work on this issue?

**Comment by smilegupta** [comment]
@ShivangiRai1310  Yes!

**Comment by iam-sakshi** [comment]
Can I work on this issue ?

**Comment by irshadjsr21** [comment]
Sorry @iam-sakshi, this issue is already taken. You can comment on `unassigned` issues. 

I'd suggest you `Watch` this repository so that you are notified when new issues are created.

**Comment by irshadjsr21** [comment]
Sorry @iam-sakshi, this issue is already taken. You can comment on `unassigned` issues. 

I'd suggest you `Watch` this repository so that you are notified when new issues are created.

**Comment by smilegupta** [comment]
Hey @ShivangiRai1310 , You were assigned this issue on 3rd October and we're expecting a PR from you by 12th October. 
Please drop a comment here if you are facing any issues and we'll try to resolve it as soon as possible.

**Comment by ShivangiRai1310** [comment]
Hii,
I'm working on the button component, I have attached the button.js and App.js (where I was testing the button) code screenshots.

I'm new to ReactJs and the code isn't working out. Would be great if someone could review and help me out.

1. Firstly - "The button should have “children” rendered inside of it." does this mean I was supposed to use class component rather than function component or something else.
2. The conditional statements are not working. 
3. The disabled property is always true even if false is passed in props. 
4. And is it possible to put custom color to the Bulma button.

![Screenshot (231)](https://user-images.githubusercontent.com/57129598/95459429-448e0c80-0991-11eb-937c-a14c49867d13.png)
![Screenshot (232)](https://user-images.githubusercontent.com/57129598/95459480-5bccfa00-0991-11eb-8899-dae39b8aa54c.png)
![Screenshot (233)](https://user-images.githubusercontent.com/57129598/95461012-5375be80-0993-11eb-9b47-8dc313ab5e68.png)
