### ISSUE TITLE
Create a navbar component.

### ISSUE THREAD

**Issue by smilegupta** [girlscript-blr/BuildWithGSBlr-Raahat#2]
- Create a navbar component as shown in the design.
- The component should be responsive so that it looks good in both desktop and mobile view.
- Add this component in HomePage

For Design reference! [Click Here](https://www.figma.com/file/TkpKfOPVtQ2XjADFp9Hhbz/Build-with-GS-BLR---Raahat?node-id=5%3A1)

**Location to save the component ```src->components->common->navbar```**

**Comment by IC1101Virgo** [comment]
Can I work on this?

**Comment by smilegupta** [comment]
@IC1101Virgo  Yes!

**Comment by IC1101Virgo** [comment]
Thank you 🧡 ! It will take 3-4 days. Hope its not a problem 😄

**Comment by Kathuria** [comment]
@IC1101Virgo  :  I am working on creating layout that requires Nav and Footer. Please update me when you are done with your changes, So I can start on creating layout with actual components. No hurry to me, you can take your time.

**Comment by IC1101Virgo** [comment]
@Kathuria Sure! I'm sorry for taking time. React is new to me and I'm still learning 😸. I'll do this as soon as possible and update you about the same 🎊

**Comment by smilegupta** [comment]
@IC1101Virgo  If you  got stuck in something! Feel free to drop a comment down this thread! I will help you out!

**Comment by IC1101Virgo** [comment]
@smilegupta It would be great if you could guide me a little bit more. To give a little context I am completely new to even HTML/CSS/JS. But I am learning 😺 .
So I started to code in the _navbar.css_ and _navbar.js_ section but no change in the site which appeared on the browser(by using **_npm run start_**) is seen.
I guess this is because my codes are not right.  I am attaching the codes. Please guide me a little bit if possible! 
If you could share some resources with me, https://bulma.io/documentation/components/navbar/ . I referred to this. 
Sorry for inconvenience 😃

![navbar_js](https://user-images.githubusercontent.com/59052808/95116572-d95ff280-0764-11eb-953a-68141023e312.png)
![navbar_css](https://user-images.githubusercontent.com/59052808/95116585-df55d380-0764-11eb-933b-553a3b3a3a9a.png)

**Comment by Kathuria** [comment]
@IC1101Virgo : Sorry to say but changes are wrong.
Here are few updates that you can work

1) Correctly chosen directory, common/Navbar (+1)
2) in Navbar.js, if you are working with components like Navbar.Brand then Navbar component should be imported (Kudos for writing correct way in react) (-1)
2) CSS is completely wrong, it's like component. Check css-tricks or w3-schools for writing css. (-1)
Like you have to add I'd or any identifier that can be class
You can check existing class and components in components/header or common/button.

**Comment by IC1101Virgo** [comment]
@Kathuria Thank you, sir, I'll look into it immediately and try again 👍 I'll also keep your points in mind 👧

**Comment by IC1101Virgo** [comment]
Hello
I would like to ask what is the deadline? I'm a little conscious about it, I don't want to hold things back.
I am learning and coding, its taking a little time. 😓

**Comment by irshadjsr21** [comment]
Hey @IC1101Virgo, You were assigned this issue on 3rd October and we're expecting a PR from you by 12th October. 
Please drop a comment here if you are facing any issues and we'll try to resolve it as soon as possible.

**Comment by IC1101Virgo** [comment]
I'll create PR by tonight. 😄
